export const authActionsType = {
    REQUEST_LOGIN:'REQUIRE_LOGIN',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    REQUEST_LOGOUT:'REQUEST_LOGOUT',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILURE:'LOGOUT_FAILURE',
};

export const categoryActionsType = {
    REQUEST_CATEGORIES:'REQUEST_CATEGORIES',
    LOAD_CATEGORIES_SUCCESS:'LOAD_CATEGORIES_SUCCESS',
    LOAD_CATEGORIES_FAIL:'LOAD_CATEGORIES_FAIL',
    REQUEST_ADD_CATEGORY: 'REQUEST_ADD_CATEGORY',
    ADD_CATEGORY_SUCCESS:'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAIL:'ADD_CATEGORY_FAIL'

};